IP        = "169.254.123.76"
bitfile   = "fft_phase_test.fpg"
adc_bits  = 16
program   = false

[snapshots]
snap_names = ["adc_snapshot"]
n_samples  = 256

[spectra]
bram_names = [["spec0", "spec1", "spec2", "spec3"]]
addr_width = 9
data_width = 64
bandwidth  = 983.04 # MHz
dBFS       = 96
reset_reg  = "cnt_rst"
acc_reg    = "acc_len"
acc_len    = 65536
