IP        = "169.254.123.76"
bitfile   = "sine_test.fpg"
program   = false

[snapshots]
n_bits  = 16
snap_names = ["adc_snapshot"]
n_samples  = 256

[spectra]
spec_names = ["spec"]
bram_names = [["spec0", "spec1", "spec2", "spec3"]]
addr_width = 9
data_width = 64
bandwidth  = 983.04 # MHz
reset_reg  = "cnt_rst"
acc_reg    = "acc_len"
acc_len    = 1000
dBFS       = 86
